import fs from 'node:fs/promises';
import path from 'node:path';
import { Workbook, SpreadsheetFile } from '@oai/artifact-tool';

const root = process.cwd();
const base = path.join(root, 'G5X_2929基因逐基因证据链');
const work = path.join(base, 'G59_work');
const d3 = path.join(root, 'D3_全基因组候选功能发现', 'D3-1-R_全基因组重扫与修正');
const utf8 = async p => (await fs.readFile(p, 'utf8')).replace(/^\uFEFF/, '');
function parseTsv(s) {
  const lines=s.replace(/\r/g,'').split('\n').filter(Boolean);
  const parseLine=line=>{const a=[];let v='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){v+='"';i++;}else q=!q;}else if(c==='\t'&&!q){a.push(v);v='';}else v+=c;}a.push(v);return a;};
  const h=parseLine(lines.shift());return lines.map(l=>Object.fromEntries(h.map((k,i)=>[k,parseLine(l)[i]??''])));
}
const attrs=s=>Object.fromEntries(s.split(';').filter(x=>x.includes('=')).map(x=>{const i=x.indexOf('=');return [x.slice(0,i),decodeURIComponent(x.slice(i+1))]}));
const source=(await utf8(path.join(work,'G59_source.txt'))).split(/\r?\n/).map(s=>{const m=s.match(/^(\d+)｜([^｜]+)｜([^｜]+)｜([^｜]+)｜(.+)$/);return m?{n:+m[1],locus:m[2],wp:m[3],coord:m[4],product:m[5]}:null}).filter(g=>g&&g.n>=2541&&g.n<=2637);
if(source.length!==97||new Set(source.map(g=>g.locus)).size!==97)throw new Error(`range integrity ${source.length}`);
const gff=await utf8(path.join(root,'B1_最新基因组与旧AFE编号映射','标准化数据','GCF_049532655.1','genomic.gff'));
const genes=new Map(),cds=new Map();for(const l of gff.split(/\r?\n/)){if(!l||l[0]==='#')continue;const f=l.split('\t'),a=attrs(f[8]);if(f[2]==='gene'&&a.gene_biotype==='protein_coding')genes.set(a.locus_tag,{coord:`${f[0]}:${f[3]}-${f[4]}(${f[6]})`,product:a.product??''});if(f[2]==='CDS'&&a.locus_tag)cds.set(a.locus_tag,a);}
const mapping=parseTsv(await utf8(path.join(root,'B1_最新基因组与旧AFE编号映射','标准化数据','旧新基因映射.tsv')));
const uniprot=parseTsv(await utf8(path.join(base,'G56_uniprot_taxon243159_20260926.tsv')));const upBy=new Map();for(const x of uniprot)for(const r of (x.RefSeq||'').split(';').map(s=>s.trim()).filter(Boolean))upBy.set(r,x);
const ann=parseTsv(await utf8(path.join(d3,'D3-1-R_注释证据表.tsv'))), xref=parseTsv(await utf8(path.join(d3,'D3-1-R_全基因跨数据库交叉引用.tsv'))), coverage=parseTsv(await utf8(path.join(d3,'D3-1-R_模型覆盖状态.tsv'))), rxmatch=parseTsv(await utf8(path.join(d3,'D3-1-R_模型反应精确匹配.tsv')));
const find=(a,l)=>a.filter(x=>x.当前locus===l), headers=['Reaction ID','Reaction Name','Reaction Formula','Confidence Level','EC Number','PMID','Subsystem','Gene-Reaction Association','Gene-Protein-Reaction Association','Protein-Reaction-Association','Fe2+ lb','Fe2+ ub','tetrathionate lb','tetrathionate ub','sulfur lb','sulfur ub','Record class','Candidate ID','Candidate group','2016 linked Reaction ID','2026 reaction object','Legacy AFE locus','Current locus','Primary evidence DOI','Evidence type','Evidence boundary','2026 action','2026 reaction score','Source ID','Score scope'];
const rows=[],ev=[],issues=[],alphaRows=[];
const rx16={
 AFE_2970:{id:'SADT',name:'sulfate adenylate transferase',formula:'h[c] + atp[c] + so4[c]  -> ppi[c] + aps[c] ',score:3,ec:'2.7.7.4',pmid:'14675496 && 19703284',subsystem:'Sulfur Metabolism ',gpr:'((AFE_2970 and AFE_2971) or (AFE_3124 and AFE_3125))',gprp:'( CysD1 (AFE_2970) and CysNC (AFE_2971) ) or ( CysD2 (AFE_3124) and CysN (AFE_3125) )',gpra:'( CysD1 and CysNC ) or ( CysD2 and CysN )',bounds:[0,1000,0,1000,0,1000]},
 AFE_2971:{id:'SADT',name:'sulfate adenylate transferase',formula:'h[c] + atp[c] + so4[c]  -> ppi[c] + aps[c] ',score:3,ec:'2.7.7.4',pmid:'14675496 && 19703284',subsystem:'Sulfur Metabolism ',gpr:'((AFE_2970 and AFE_2971) or (AFE_3124 and AFE_3125))',gprp:'( CysD1 (AFE_2970) and CysNC (AFE_2971) ) or ( CysD2 (AFE_3124) and CysN (AFE_3125) )',gpra:'( CysD1 and CysNC ) or ( CysD2 and CysN )',bounds:[0,1000,0,1000,0,1000]},
 AFE_2973:{id:'BPNT',name:'3,5-bisphosphate nucleotidase',formula:'h2o[c] + pap[c]  -> pi[c] + amp[c] ',score:2,ec:'3.1.3.7',pmid:14675496,subsystem:'Cysteine Metabolism',gpr:'AFE_2973',gprp:'CysQ (AFE_2973)',gpra:'CysQ',bounds:[0,1000,0,1000,0,1000]},
 AFE_2924:{id:'PGI1',name:'glucose-6-phosphate isomerase',formula:'g6p-B[c]  <=> f6p-B[c] ',score:2,ec:'5.3.1.9',pmid:19077236,subsystem:'Glycolysis/Gluconeogenesis',gpr:'AFE_2924',gprp:'Pgi (AFE_2924)',gpra:'Pgi',bounds:[-1000,1000,-1000,1000,-1000,1000]},
 AFE_2948:{id:'NNAT',name:'nicotinate-nucleotide adenylyltransferase',formula:'h[c] + atp[c] + nicrnt[c]  <=> ppi[c] + dnad[c] ',score:2,ec:'2.7.7.18',pmid:'',subsystem:'( Cofactor and Prosthetic Group Biosynthesis ) or ( NAD biosynthesis )',gpr:'AFE_2948',gprp:'NadD (AFE_2948)',gpra:'NadD',bounds:[-1000,1000,-1000,1000,-1000,1000]}
};
for(const g of source){
 const id=genes.get(g.locus),c=cds.get(g.locus);if(!id||c?.protein_id!==g.wp)throw new Error(`GFF/CDS mismatch ${g.n}`);
 const mp=mapping.filter(x=>(x.当前GCF049位点??'').split('|').includes(g.locus)&&x.当前蛋白ID===g.wp&&x.映射状态==='完全匹配');const afe=mp.length===1?mp[0].旧AFE位点:'未确认';
 const aa=find(ann,g.locus),xx=find(xref,g.locus),cv=find(coverage,g.locus),rm=find(rxmatch,g.locus),u=upBy.get(g.wp);
 const d3sum=aa.map(x=>`${x.数据库}:${x.记录ID} [${x.证据字段}; ${x['证据等级/限制']}]`).join(' | ');
 const xsum=xx.map(x=>`${x.来源}:${x.对象} [${x['映射/交叉引用']}; ${x.证据类型}]`).join(' | ');
 const model=rm.map(x=>x['2016 GPR反应']).filter(Boolean).join('; ');
 const isChemical=/glucose-6-phosphate isomerase|nicotinate-nucleotide adenylyltransferase|mannose-1-phosphate guanylyltransferase|sulfate adenylyltransferase|bisphosphate nucleotidase|linear amide C-N hydrolase|GDP-mannose 4,6-dehydratase|glutamine amidotransferase|transpeptidase|polyprenyl synthetase/i.test(g.product);
 const action=model?'仅更新证据或编号':'证据不足暂缓';
 const unresolved=`不从产品名直接定反应。逐行数据库记录已按WP/AFE提取到D3证据表，原始记录是否本株实验证据、底物/产物、辅因子、方向、区室/膜侧、复合体/同工酶仍按该行证据边界处理；具体待核点见本表。${u?'2026-09-26 UniProt快照命中，记录版本/更新时间一并收录；自动/审校条目不自动等于该株实验。':'2026-09-26 UniProt快照未找到该WP；此项不代表功能阴性。'}`;
 const evidence=`GFF/CDS exact: ${g.locus}, ${g.wp}, ${id.coord}; product=${g.product}. B1=${afe}${mp.length===1?` (${mp[0].映射方法}; ${mp[0].映射状态})`:' (no unique exact-locus+WP match)'}. UniProt snapshot=${u?`${u.Entry}; reviewed=${u.Reviewed}; ${u['Protein names']}; EC=${u['EC number']}; InterPro=${u.InterPro}; Pfam=${u.Pfam}; KEGG=${u.KEGG}`:'not found by exact WP'}. D3 coverage=${cv.map(x=>x.旧模型GPR覆盖).filter(Boolean).join(';')||'not resolved'}; reaction matching lead=${model||'none'}; database leads=${d3sum||'none'}; xrefs=${xsum||'none'}.`;
 rows.push([g.n,g.locus,g.wp,g.coord,g.product,afe,mp.length===1?`${mp[0].映射方法}; ${mp[0].映射状态}`:'not confirmed',u?`${u.Entry} (${u.Reviewed}; v${u['Entry version']}; modified ${u['Date of last modification']})`:'not found in 2026-09-26 snapshot',model,action,evidence,unresolved,`G59-C-${g.n}`,'GCF_049532655.1 GFF/CDS; B1; UniProt TSV 2026-09-26; D3-1-R']);
 // One Alpha-compatible row per gene, without inventing chemistry or scores.
 rows.at(-1).push();
 const rx=rx16[afe];
 if(rx){const a=Array(30).fill('');a.splice(0,16,rx.id,rx.name,rx.formula,rx.score,rx.ec,rx.pmid,rx.subsystem,rx.gpr,rx.gprp,rx.gpra,...rx.bounds);a[16]='2016 linked reaction audit';a[17]=`G59-C-${g.n}-${rx.id}`;a[18]='G59';a[19]=rx.id;a[20]='2016 iMC507 Table 1 exact row; equation and original score retained';a[21]=afe;a[22]=g.locus;if(afe==='AFE_2970'||afe==='AFE_2971')a[23]='10.13560/j.cnki.biotech.bull.1985.2016.02.017';a[24]=afe==='AFE_2970'||afe==='AFE_2971'?'2016 same-strain transcript/recombinant-enzyme study; assay-to-reaction mapping incomplete in abstract':'2016 model record; related pathway sources are listed in Paper sources';a[25]=afe==='AFE_2970'||afe==='AFE_2971'?'Paper reports cysD-1/cysNC co-transcription and recombinant enzyme work among candidates. Public abstract does not specify which assay measured this reaction; retain original 2016 score, do not infer direction/localization from abstract.':'Confirms the 2016 model content. Gene-specific support and the limits of each paper are detailed in Paper sources.';a[26]='仅更新证据或编号';a[27]=rx.score;a[28]=afe==='AFE_2970'||afe==='AFE_2971'?'G59-C-SRC-2016; G59-C-SRC-2016CN; G59-C-SRC-2003':'G59-C-SRC-2016; G59-C-SRC-2008';a[29]=`2016 reaction score ${rx.score}; score applies to the original reaction only`;alphaRows.push(a);}
 if(g.locus==='RU820_RS13785'){
  const a=Array(30).fill('');a.splice(0,16,'','3′-phosphoadenylyl-sulfate phosphatase','paps[c] + h2o[c] -> aps[c] + pi[c]',2,'3.1.3.7','','Cysteine metabolism','AFE_2973','CysQ (AFE_2973)','CysQ',0,1000,0,1000,0,1000);a[16]='2026 reaction candidate';a[17]='G59-C-2620-CysQ-PAPS';a[18]='G59';a[19]='';a[20]='Add separate candidate reaction: 3′-phosphoadenylyl sulfate (PAPS) + water → adenosine 5′-phosphosulfate (APS) + phosphate; reference RHEA:77639 / KEGG R00508';a[21]=afe;a[22]=g.locus;a[23]='';a[24]='UniProt/KEGG/Rhea specific enzyme annotation; no direct current-strain PAPS-phosphatase assay found';a[25]='Databases associate CysQ/EC 3.1.3.7 with this exact hydrolysis. Substrate assignment is annotation/homology-level; in-strain activity, cytosolic localization, and physiological direction/flux are unverified.';a[26]='新增 reaction candidate';a[27]=2;a[28]=`G59-C-UP-${g.n}; G59-C-D3-${g.n}-KEGG; G59-C-D3-${g.n}-Rhea:RHEA:77639`;a[29]='2026 candidate score 2: exact chemistry linked by function annotation/homology; not wet-lab confirmation; iMC507 BPNT score 2 applies only to PAP hydrolysis';alphaRows.push(a);rows.at(-1)[9]='新增 reaction candidate（CysQ PAPS phosphatase; score 2）';rows.at(-1)[11]=`Existing BPNT PAP + H2O -> AMP + Pi retained. Separate Rhea RHEA:77639 / KEGG R00508 candidate: PAPS + H2O -> APS + Pi; curation/homology evidence only, local activity and direction unresolved. ${rows.at(-1)[11]}`;
 }
 const alpha=Array(30).fill('');alpha[16]='gene-level evidence review';alpha[17]=`G59-C-${g.n}`;alpha[18]='G59';alpha[19]=model;alpha[20]=rx?`2016 Table 1 linkage ${rx.id}; original row copied separately`:(model?`D3 reports model linkage ${model}; original row not independently verified here`:'No precise reaction established from reviewed evidence');alpha[21]=afe;alpha[22]=g.locus;alpha[24]=u?'UniProt snapshot; D3 aggregate cross-database annotations':'NCBI/GFF identity and D3 aggregate annotations';alpha[25]=unresolved;alpha[26]=rx?'仅更新证据或编号':action;alpha[27]=rx?rx.score:'不评分';alpha[28]=`G59-C-ID-${g.n}; G59-C-UP-${g.n}; G59-C-D3-${g.n}`;alpha[29]=rx?`2016 reaction score ${rx.score} only; current evidence not independently rescored`:'Reaction not chemically defined; no confidence score assigned';alphaRows.push(alpha);
 ev.push([`G59-C-ID-${g.n}`,g.n,g.locus,'NCBI RefSeq GFF/CDS','GCF_049532655.1 / '+g.wp,'sequence identity',`${id.coord}; ${g.product}; exact CDS protein_id match`,'current strain RefSeq annotation','B1 standardization/GCF_049532655.1 genomic.gff','Product is an annotation, not proof of enzyme activity']);
 ev.push([`G59-C-B1-${g.n}`,g.n,g.locus,'B1 historical map',afe,'exact locus+WP mapping',mp.length===1?`${mp[0].映射方法}; ${mp[0].映射状态}`:'No unique exact mapping','sequence identity mapping','旧新基因映射.tsv','Do not infer AFE from RU820 numbering']);
 if(u)ev.push([`G59-C-UP-${g.n}`,g.n,g.locus,'UniProt snapshot',u.Entry,'protein name, review status, EC, InterPro, Pfam, KEGG, entry version/update',`${u.Reviewed}; ${u['Protein names']}; EC ${u['EC number']}; InterPro ${u.InterPro}; Pfam ${u.Pfam}; KEGG ${u.KEGG}; version=${u['Entry version']}; modified=${u['Date of last modification']}`,'bulk snapshot 2026-09-26; details not independently verified','G56_uniprot_taxon243159_20260926.tsv','Snapshot mapping via exact current WP; reviewed status / homology annotation is not direct reaction evidence']);
 else ev.push([`G59-C-UP-${g.n}`,g.n,g.locus,'UniProt snapshot','', 'exact-WP lookup', 'No entry in 2026-09-26 strain-wide UniProt TSV','accession absence in snapshot','G56_uniprot_taxon243159_20260926.tsv','Absence is not evidence of absent function']);
 for(const a of aa)ev.push([`G59-C-D3-${g.n}-${a.数据库}-${a.记录ID}`,g.n,g.locus,a.数据库,a.记录ID,a.证据字段,a.记录内容,a['证据等级/限制'],a.来源文件,`D3 aggregate lead; must re-open primary entry; not independent wet-lab evidence`]);
 for(const x of xx)ev.push([`G59-C-XREF-${g.n}-${x.来源}-${x.对象}`,g.n,g.locus,x.来源,x.对象,x['映射/交叉引用'],x.证据类型,x.文献ID,x.官方链接,'Cross-reference trail only; duplicated database provenance counts once']);
 let issue=unresolved;
 if(g.locus==='RU820_RS13480'||g.locus==='RU820_RS13505')issue='Ammonium transporter candidates (KEGG K03320); D3 BioCyc has a generic AMMONIUM/PROTON transport object but no substrate-side, stoichiometric coupling or proton stoichiometry demonstrated. Two loci are paralog candidates; do not merge into an OR GPR without independent transport evidence. UniProt/InterPro family supports transporter family only; direction, NH3/NH4+ form and energy coupling unresolved.';
 if(g.locus==='RU820_RS13545')issue='PGI: KEGG afr:AFE_2924 K01810/EC 5.3.1.9/R00771; Rhea RHEA:11816 gives alpha-D-glucose 6-phosphate = beta-D-fructose 6-phosphate; BioCyc PGLUCISOM-RXN. iMC507 PGI1 formula/GPR/score copied in Alpha tab. 2008 genome paper is a prediction/model source, not direct assay of WP_009568056.1; no new model action supported.';
 if(g.locus==='RU820_RS13650'||g.locus==='RU820_RS13655')issue='Methionine-sulfoxide repair enzymes MsrB (R-form) / MsrA (S-form) are stereospecific family assignments; likely reducing equivalents from thioredoxin systems are not modeled as exact gene-specific reaction in this pass. Separate A/S substrates; do not conflate as one enzyme or infer same redox partner. Cofactor/electron donor stoichiometry and in vivo direction not verified.';
 if(g.locus==='RU820_RS13665')issue='NadD / nicotinate-nucleotide adenylyltransferase: iMC507 NNAT record copied with original formula, GPR, confidence 2 and bounds. Reaction is nicotinate ribonucleotide + ATP + H+ ⇌ deamido-NAD + PPi per that model. Original paper/source for this exact current protein not found; keep 2016 reaction score separate from current direct evidence.';
 if(g.locus==='RU820_RS13770'||g.locus==='RU820_RS13775')issue='SADT complex: current proteins map exactly to AFE_2970 CysD1 and AFE_2971 CysNC; iMC507 original GPR retains ((AFE_2970 and AFE_2971) or (AFE_3124 and AFE_3125)), score 3. Rhea RHEA:18133 gives sulfate + ATP + H+ → APS + diphosphate; KEGG EC 2.7.7.4 and BioCyc agree as cross-references. A 2016 same-strain paper (DOI 10.13560/j.cnki.biotech.bull.1985.2016.02.017) reports cysD-1/cysNC co-transcription and recombinant enzyme activity among key candidate genes, but its public abstract does not identify which protein’s assay measured which precise substrate/product; do not use it alone to reassign reaction direction or subunit chemistry. Retain original iMC507 score 3. The 2003 genome reconstruction also associates cysNC2 with capsule neighborhood/suggested PAPS use; that role is a hypothesis, not a second confirmed activity.';
 if(['RU820_RS13725','RU820_RS13730','RU820_RS13740','RU820_RS13745','RU820_RS13750','RU820_RS13755','RU820_RS13760','RU820_RS13765'].includes(g.locus))issue='EPS/capsule neighborhood: mannose-1-phosphate guanylyltransferase/isomerase plus capsule transporter, ABC ATPase, glycosyltransferase, sulfotransferase and methyltransferase annotations are present. D3/UniProt family and neighborhood do not determine sugar donor/acceptor, linkage, modification position, transporter substrate, ATP stoichiometry or whether proteins form a single required complex. No GPR AND/OR assigned from adjacency; primary strain-specific substrate assays not located.';
 issues.push([g.n,g.locus,'Gene-specific reaction/model review',issue]);
}
const wb=Workbook.create();
const colName=n=>{let s='';while(n){const r=(n-1)%26;s=String.fromCharCode(65+r)+s;n=Math.floor((n-1)/26);}return s;};
function addSheet(name,head,data){const s=wb.worksheets.add(name);const last=colName(head.length);s.getRange(`A1:${last}${data.length+1}`).values=[head,...data];s.freezePanes.freezeRows(1);s.getRange(`A1:${last}1`).format={fill:'#1F4E78',font:{bold:true,color:'#FFFFFF'},wrapText:true};s.getRange(`A1:${last}${data.length+1}`).format.wrapText=true;return s;}
addSheet('Gene index',['Total no.','Current locus','WP protein_id','GFF coordinates','Current product','Legacy AFE locus','B1 mapping basis/status','UniProt snapshot','2016 linked reaction leads','Action','Evidence chain summary','Unresolved points','Associated review row ID','Identity/source basis'],rows);
addSheet('Alpha review rows',headers,alphaRows);
addSheet('Evidence ledger',['Source ID','Total no.','Current locus','Database/source','Record accession','Evidence field','Description/value','Evidence grade/source type','Source file/link','Source limit'],ev);
addSheet('Paper sources',['Source ID','Full citation','Year','DOI','Source type','Strain','Experimental type','Genes / proteins studied','Related reaction / candidate IDs','What was directly measured','Applicable confidence level','Evidence limitation'],[
 ['G59-C-SRC-2003','Valdés J, Veloso F, Jedlicki E, Holmes D. Metabolic reconstruction of sulfur assimilation in the extremophile Acidithiobacillus ferrooxidans based on genome analysis. BMC Genomics 4, 51. PMID:14675496.',2003,'10.1186/1471-2164-4-51','genome-based reconstruction','A. ferrooxidans; genome reference predates GCF_049532655.1','comparative genomics / pathway reconstruction','sulfur assimilation genes including sulfate-activation pathway','SADT; BPNT; CysD/CysN/CysQ','Genome-based pathway/gene assignments; no enzyme turnover measured for the present WP proteins.','2 (indirect; reaction-specific only if criteria fit)','Prior genome/protein versions; not a direct biochemical assay of these gene products.'],
 ['G59-C-SRC-2009S','Quatrini R, Appia-Ayme C, Denis Y, et al. Extending the models for iron and sulfur oxidation in the extreme acidophile Acidithiobacillus ferrooxidans. BMC Genomics 10, 394. PMID:19703284.',2009,'10.1186/1471-2164-10-394','genome-based sulfur model with transcript profiling and qRT-PCR','ATCC 23270 (NC_011206 reference)','microarray and qRT-PCR; pathway reconstruction','sulfur oxidation / sulfur metabolism genes; not a direct assay of CysD/CysN enzyme catalysis','SADT context; sulfur metabolism context','Transcription abundance under sulfur-related conditions and predicted pathway context; not purified-enzyme activity or a CysD/CysN-specific knockout.','2 (indirect)','Supports expression/pathway context. Does not independently establish exact catalytic chemistry or complex stoichiometry for this strain.'],
 ['G59-C-SRC-2016CN','Zheng CL, Wang D, Zhang L, Chen MJ, Ma HW, Jiang ZY. The Identification and Analysis of Sulfate-assimilation Related Genes in Acidithiobacillus ferrooxidans. Biotechnology Bulletin 32(2):131–139. DOI:10.13560/j.cnki.biotech.bull.1985.2016.02.017.',2016,'10.13560/j.cnki.biotech.bull.1985.2016.02.017','original same-strain gene/transcript and recombinant-protein study','ATCC 23270','RT-PCR/gel co-transcription; cloned, expressed, purified recombinant proteins and enzyme-activity assays','candidate cysD-1 and cysNC co-transcription; abstract says enzyme activities measured for key genes but does not specify which assays/substrates','SADT / CysD1-CysNC pair','Public abstract directly reports co-transcription of cysD-1 with cysNC and recombinant enzyme-activity work among candidate genes. Exact assay-to-protein and substrate/product mapping remains unavailable from the abstract.','3 only if full-text assay is shown to correspond to the exact SADT reaction; otherwise 2 for indirect support','Do not attribute a precise reaction, direction, localization, or enzyme stoichiometry until the article tables/full text establish assay substrate/product and cloned protein identities. Original iMC507 score 3 is preserved as historical value.'],
 ['G59-C-SRC-2012ATPS-EXCL','Jaramillo ML, Abanto M, Quispe RL, et al. Cloning, expression and bioinformatics analysis of ATP sulfurylase from Acidithiobacillus ferrooxidans ATCC 23270 in Escherichia coli. Bioinformation 8(15):694–704. PMID:23055613.',2012,'10.6026/97320630008695','same-strain recombinant enzyme assay; excluded from G59 assignments','ATCC 23270','atpS from FM177944 cloned and expressed in E. coli; extract assay measures ATP formation from APS + PPi','atpS / Sat protein CAQ76453, 557 aa; paper/reconstruction locate it at old AFE_0539, outside G59 current loci','exclusion control for SADT AFE_2970/AFE_2971','Recombinant protein activity measured in the APS + PPi → ATP + sulfate direction (reported ATP-formation assay). Full-text gene is atpS/FM177944/CAQ76453 and the same-strain model context identifies Sat as AFE_0539.','4 for the tested reverse reaction on that distinct protein only; no score transfer to G59 SADT','Direct biochemistry supports a distinct homooligomeric ATP sulfurylase (Sat/AFE_0539); it does not establish the AFE_2970/AFE_2971 CysD1/CysNC complex or its forward direction. Not counted as G59 gene evidence.'],
 ['G59-C-SRC-2008','Valdés J, Pedroso I, Quatrini R, et al. Acidithiobacillus ferrooxidans metabolism: from genome sequence to industrial applications. BMC Genomics 9, 597. PMID:19077236.',2008,'10.1186/1471-2164-9-597','genome analysis / functional prediction','ATCC 23270','genome annotation and metabolic reconstruction','central metabolism and other predicted functions; no gene-specific assay for PGI/NadD/CysQ in this review','PGI1; NNAT; BPNT','Genome-based predictions and pathway models; not direct enzyme activity measurements for the current proteins.','2 (indirect)','Review/model evidence only for these reactions; not gene-specific biochemical confirmation.'],
 ['G59-C-SRC-2016','Campodonico MA, Vaisman D, Castro JF, et al. Acidithiobacillus ferrooxidans’s comprehensive model driven analysis of the electron transfer metabolism and synthetic strain design for biomining applications. Metab Eng Commun 3:84–96. DOI:10.1016/j.meteno.2016.03.003.',2016,'10.1016/j.meteno.2016.03.003','genome-scale model; iMC507 baseline','ATCC 23270','model reconstruction and in silico analysis','iMC507 reaction/GPR records','SADT; BPNT; PGI1; NNAT','Reports model equations, GPRs, confidence scores, and medium bounds; model record itself is not a gene-specific wet-lab measurement.','original reaction scores copied verbatim (2 or 3)','Preserve original score as the 2016 model’s score; do not transfer it to any new GPR or different chemistry.']
]);
addSheet('Open issues',['Total no.','Current locus','Topic','Status/next verification'],issues);
addSheet('Readme',['Item','Result'],[
 ['Assignment','G59; totals 2541–2637 inclusive'],['Count',source.length],['First/last',`${source[0].locus} / ${source.at(-1).locus}`],['Genome baseline','GCF_049532655.1; NZ_CP136162.1; exact GFF gene-to-CDS protein_id join'],['Drive instructions','Read G5X Series General Instructions and G59 assignment; Alpha A–P/Q–AD columns and reaction-level 2016 confidence standard retained'],['UniProt cache','G56 whole-proteome UniProt snapshot dated 2026-09-26; exact WP lookup; Entry version and modification date captured; reviewed status is not direct biochemical evidence'],['D3 evidence','D3-1-R aggregate tables supply NCBI/B1/KEGG/BioCyc/BRENDA/Rhea leads and model coverage. Accessions, record payloads, and source limits are in Evidence ledger'],['Primary papers','2003 genome-based sulfur assimilation, 2008 ATCC 23270 genome reconstruction, 2009 sulfur transcript profiling, and 2016 iMC507 model paper listed in Paper sources with scope limits'],['2016 comparison','SADT/BPNT/PGI1/NNAT original A–P fields and bounds copied from mmc1.xlsx. PMID numeric cells stay numeric. Original scores retained as scores of 2016 reactions'],['High-value reviews','CysD/CysN SADT pair, CysQ, two Amt transporters, PGI, MsrA/B, NadD, and capsule/EPS neighborhood have focused issue notes; no unproven transporter stoichiometry or subunit GPR is assigned'],['Score','4 direct biochemical; 3 corresponding knockout/physiology; 2 indirect evidence; 1 model-only. Original scores are never transferred to new chemistry. Undefined candidates remain unscored'],['Completion status','97 identities and local database leads assembled. This is a review workfile, not a claim that every primary database page and same-strain gene-specific experiment has been independently closed.'],['Limitations','D3 aggregates are cached cross-reference leads; database lineage may be inherited. TCDB and independent MetaCyc/BRENDA access need explicit review for transport/EPS genes.']]);
for(const s of wb.worksheets.items){s.getUsedRange()?.format?.autofitColumns?.();}
wb.recalculate();
await fs.mkdir(work,{recursive:true});const out=await SpreadsheetFile.exportXlsx(wb);await out.save(path.join(work,'part_c.xlsx'));
console.log(JSON.stringify({out:path.join(work,'part_c.xlsx'),count:source.length,sheets:wb.worksheets.items.map(s=>s.name),rows:rows.length,evidence:ev.length}));
