#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import datetime as dt
import json
from pathlib import Path
import xlrd

ROOT = Path(r"D:\嗜酸氧化亚铁硫杆菌")
ORIG = ROOT / "01_原始数据" / "02_2016_iMC507原始模型"
PAPER = ROOT / "02_论文" / "02_基因组与代谢模型" / "2016主要模型GEM.pdf"
OUT = ROOT / "baseline_v0"


def now_iso():
    return dt.datetime.now(dt.timezone(dt.timedelta(hours=8))).isoformat(timespec="seconds")


def read_table1():
    book = xlrd.open_workbook(str(ORIG / "mmc1.xls"), on_demand=True)
    s = book.sheet_by_name("Table 1")
    rows = []
    for r in range(2, s.nrows):
        rid = s.cell_value(r, 0)
        if rid == "" or rid is None:
            continue
        def cv(c):
            v = s.cell_value(r, c)
            if v == "":
                return ""
            if isinstance(v, float) and v.is_integer():
                return int(v)
            return v
        rows.append(dict(reaction_id=str(rid), equation=str(cv(2)), lb_fe2=cv(10), ub_fe2=cv(11), lb_ttton=cv(12), ub_ttton=cv(13), lb_tsul=cv(14), ub_tsul=cv(15)))
    book.release_resources()
    return rows


def read_table5():
    book = xlrd.open_workbook(str(ORIG / "mmc1.xls"), on_demand=True)
    s5 = book.sheet_by_name("Table 5")
    points = []
    def isnum(v):
        return isinstance(v, (int, float)) and not isinstance(v, bool)
    for r in range(3, s5.nrows):
        def cv5(c):
            v = s5.cell_value(r, c)
            return v if v != "" else None
        fe2_mu, fe2_up, fe2_o2, fe2_co2 = cv5(0), cv5(1), cv5(2), cv5(3)
        s4_mu, s4_up, s4_co2 = cv5(5), cv5(6), cv5(7)
        s2_mu, s2_up, s2_co2 = cv5(9), cv5(10), cv5(11)
        if isnum(fe2_mu):
            points.append(dict(condition="FIM", electron_donor="fe2", mu=fe2_mu, donor_uptake=fe2_up, o2_uptake=fe2_o2, h2co3_uptake=fe2_co2))
        if isnum(s4_mu):
            points.append(dict(condition="TTM", electron_donor="s4o6", mu=s4_mu, donor_uptake=s4_up, o2_uptake=None, h2co3_uptake=s4_co2))
        if isnum(s2_mu):
            points.append(dict(condition="TSM", electron_donor="s2o3", mu=s2_mu, donor_uptake=s2_up, o2_uptake=None, h2co3_uptake=s2_co2))
    book.release_resources()
    return points


def status(lb, ub):
    lb = float(lb)
    ub = float(ub)
    if lb == 0 and ub == 0:
        return "closed"
    if lb < 0 and ub > 0:
        return "open_free"
    if lb < 0 and ub == 0:
        return "uptake_only"
    if lb == 0 and ub > 0:
        return "export_only"
    if lb < 0 and ub < 0 and lb == ub:
        return "fixed_uptake"
    if lb > 0 and lb == ub:
        return "fixed_export"
    return "other"


def build_exchanges(rows):
    exch = [r for r in rows if r["reaction_id"].startswith("Ex_")]
    out = []
    for r in exch:
        out.append(dict(
            reaction_id=r["reaction_id"],
            equation=r["equation"].strip(),
            FIM=dict(lower_bound=r["lb_fe2"], upper_bound=r["ub_fe2"], status=status(r["lb_fe2"], r["ub_fe2"])),
            TTM=dict(lower_bound=r["lb_ttton"], upper_bound=r["ub_ttton"], status=status(r["lb_ttton"], r["ub_ttton"])),
            TSM=dict(lower_bound=r["lb_tsul"], upper_bound=r["ub_tsul"], status=status(r["lb_tsul"], r["ub_tsul"])),
        ))
    return out


def main():
    rows = read_table1()
    points = read_table5()
    exchanges = build_exchanges(rows)

    # Table 5 variable roles, derived from Methods 2.5 / Supp Note 3.
    variable_roles = {
        "growth_rate_mu_h_minus1": {
            "role": "VALIDATION_TARGET",
            "basis": "Methods 2.5: Fitness compares FBA predictions to experimental growth rate; Supp Note 3: model validated by comparing growth predictions with experimental values; FBA objective is growth maximization.",
        },
        "electron_donor_uptake_mmol_gDW_h": {
            "role": "VALIDATION_TARGET",
            "basis": "Methods 2.5: Fitness compares FBA predictions for fe2/ttton/tsul uptake rate; the donor exchange is left open (electron donor allowed to freely enter), so its uptake is predicted, not fixed as input.",
        },
        "h2co3_inorganic_carbon_uptake_mmol_gDW_h": {
            "role": "MODEL_INPUT_CONSTRAINT",
            "basis": "Methods 2.5: each of the 20 metabolism-specific models was generated by setting the specific experimental h2co3 uptake rate.",
        },
        "o2_uptake_mmol_gDW_h": {
            "role": "VALIDATION_TARGET",
            "basis": "Methods 2.5: Fitness compares FBA predictions for o2 uptake rate; o2 exchange is left open (-1000/1000). Only present for FIM in Table 5.",
        },
    }

    # Encode per-point measurement roles.
    encoded_points = []
    for p in points:
        meas = {
            "growth_rate_mu_h_minus1": {"value": p["mu"], "role": "VALIDATION_TARGET"},
            "electron_donor_uptake_mmol_gDW_h": {"value": p["donor_uptake"], "role": "VALIDATION_TARGET"},
            "h2co3_inorganic_carbon_uptake_mmol_gDW_h": {"value": p["h2co3_uptake"], "role": "MODEL_INPUT_CONSTRAINT"},
        }
        if p["o2_uptake"] is not None:
            meas["o2_uptake_mmol_gDW_h"] = {"value": p["o2_uptake"], "role": "VALIDATION_TARGET"}
        else:
            meas["o2_uptake_mmol_gDW_h"] = {"value": None, "role": "NOT_REPORTED_IN_TABLE5"}
        encoded_points.append(dict(condition=p["condition"], electron_donor=p["electron_donor"], measurements=meas))

    special_analysis_scenarios = [
        {
            "scenario_id": "minimal_media_table1_columns",
            "h2co3_mmol_gDW_h": 2.0,
            "conditions": ["FIM", "TTM", "TSM"],
            "electron_donor": "condition-specific donor (fe2 / ttton / tsul), exchange left open on the uptake side",
            "source": "mmc1.xls Table 1 cols 11-16 (Minimal Media for fe2/ttton/tsul); Ex_h2co3[e] fixed lb=ub=-2",
            "note": "This is the published model minimal-media setting, not an experimental uptake and not a universal growth constraint; the value 2.0 also appears as the normalization below.",
        },
        {
            "scenario_id": "flux_distribution_normalization",
            "h2co3_mmol_gDW_h": 2.0,
            "conditions": ["FIM", "TTM", "TSM"],
            "electron_donor": "corresponding donor allowed to freely enter the system",
            "source": "Results Fig 2; Fig 3 caption; Supplementary Note 4",
            "note": "FBA maximizing BOF with h2co3 uptake normalized to 2 mmol/gDW/h to compare flux states across donors.",
        },
        {
            "scenario_id": "reaction_knockdown_fim",
            "h2co3_mmol_gDW_h": 2.0,
            "conditions": ["FIM"],
            "electron_donor": "fe2 and o2 freely enter/leave",
            "source": "Methods 2.7; Results Fig 4",
            "note": "Individual reaction knock-down with external CO2 transport constraints (0/50/100%).",
        },
        {
            "scenario_id": "reaction_essentiality_analysis",
            "h2co3_mmol_gDW_h": 2.34,
            "conditions": ["FIM", "TTM", "TSM"],
            "electron_donor": "condition-specific donor (Methods 2.6 describes sequential reaction removal)",
            "source": "Methods 2.6 (Reaction essentiality analysis)",
            "note": "h2co3 uptake set to 2.34 mmol/gDW/h; reactions removed by lb=ub=0; growth>0 = non-lethal knockout.",
        },
        {
            "scenario_id": "eps_growth_coupled_knockout_design",
            "h2co3_mmol_gDW_h": 2.34,
            "conditions": ["FIM"],
            "electron_donor": "fe2 and o2 freely enter/leave; external metabolic CO2 transport step added",
            "source": "Methods 2.8 (Reaction knock-out simulations)",
            "note": "Single/double/triple knockouts for growth-coupled EPS production; 134 designs reported.",
        },
    ]

    energy_parameters = {
        "GAM": {
            "value": 139,
            "units": "mmol ATP/gDW",
            "where_embedded": "biomass objective function Afe_biomass_mc507_WT_139p0M (139 h2o + 139.1 atp on the reactant side)",
            "applies_to": [
                "final fitted model used for the 20-point validation (genetic algorithm fit)",
                "electron-transfer flux-distribution analyses",
                "reaction essentiality / knock-down / knock-out / EPS design analyses",
            ],
            "excluded_from": [
                "minimal medium formulation and gap-filling (Methods 2.4: GAM and NGAM were not considered)",
            ],
            "basis": "Methods 2.2/2.5; Supplementary Note 3; biomass reaction label 'with 139 GAM estimate'.",
        },
        "NGAM_ATPM": {
            "value": 3.475,
            "units": "mmol/gDW/h",
            "relation": "2.5% of GAM (Feist et al., 2006); 139 * 0.025 = 3.475",
            "where_embedded": "ATPM reaction (ATP maintenance requirement), lb=ub=3.475 in mmc1.xls Table 1",
            "applies_to": [
                "final fitted model used for validation and downstream analyses (same scope as GAM)",
            ],
            "excluded_from": [
                "minimal medium formulation and gap-filling (Methods 2.4)",
            ],
            "basis": "Methods 2.5 (NGAM set as 2.5% of GAM); mmc1.xls Table 1 ATPM row.",
        },
    }

    scenario = dict(
        schema_version="2.0",
        title="2016 iMC507 scenario constraints (traceable run-condition definition, semantics-separated)",
        generated_at=now_iso(),
        note="Defines 2016 model run conditions, not a wet-lab medium recipe. Open exchange bounds are availability flags, not uptake rates. Values not explicitly reported are not guessed.",
        source_files=dict(
            sbml=str((ORIG / "mmc3.xml").relative_to(ROOT)),
            reaction_table=str((ORIG / "mmc1.xls").relative_to(ROOT)),
            supplementary_word=str((ORIG / "mmc2.docx").relative_to(ROOT)),
            paper=str(PAPER.relative_to(ROOT)),
        ),
        model_scope=dict(
            total_reactions_sbml=615,
            exchange_reactions=28,
            non_exchange_reactions=587,
            metabolites=573,
            genes=507,
            compartments=["c", "e", "p"],
            objective_reaction="Ex_bio[e] (R_Ex_bio_LSQBKT_e_RSQBKT_)",
        ),
        base_medium_definition=dict(
            carbon_source=dict(
                metabolite="H2CO3 (inorganic carbon / CO2)",
                role="sole carbon source",
                availability="available (uptake)",
                note="The published minimal media (mmc1.xls Table 1) fixes Ex_h2co3[e] at -2/-2; that fixed value is a model normalization, not an experimental uptake. Per-point experimental H2CO3 uptake is in experimental_validation_table5; other fixed values (2.0, 2.34) are in special_analysis_scenarios.",
            ),
            electron_donors=dict(
                FIM="fe2 (ferrous iron)",
                TTM="s4o6 (tetrathionate)",
                TSM="s2o3 (thiosulfate)",
            ),
            nitrogen_source="N2 (dinitrogen fixation, NITF); NH4 exchange is closed",
            interpretation_rule="An open bound (e.g. -1000/1000) means the compound is freely available to enter/leave; it is NOT a measured uptake rate. Measured uptake rates only appear in experimental_validation_table5.",
            exchanges=exchanges,
        ),
        experimental_validation_table5=dict(
            point_count=len(points),
            source="2016 paper Supplementary Table 5 (mmc1.xls sheet Table 5)",
            variable_roles=variable_roles,
            points=encoded_points,
            residual_ambiguity="Methods 2.5 writes '20 different experimental points specifying the growth rate, h2co3 uptake rate, o2 uptake rate (only for FIM), and the corresponding final electron donor ... were used for simulations'. Only h2co3 is explicitly singled out as 'set' per model; growth, donor uptake and o2 uptake appear in the fitness comparison as FBA predictions, so they are classified as VALIDATION_TARGET. The 'used for simulations' phrasing is loose, but no variable is left as REPORTED_BUT_ROLE_REQUIRES_CONFIRMATION because the Methods fitness-comparison sentence resolves the roles.",
        ),
        special_analysis_scenarios=special_analysis_scenarios,
        energy_parameters=energy_parameters,
    )

    out = OUT / "scenario_definition" / "2016_scenario_constraints.json"
    out.write_text(json.dumps(scenario, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("revision written")
    print("points=", len(points), "exchanges=", len(exchanges))


if __name__ == "__main__":
    main()
