"""Create Alpha-style source register for the G51 working review."""
import concurrent.futures
import json
import time
import urllib.parse
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
curated = json.loads((HERE / "curated_findings.json").read_text(encoding="utf-8"))
DOIS = sorted({doi.strip() for item in curated.values() for doi in item.get("evidence_doi", "").split(";") if doi.strip()})
CACHE = HERE / "crossref_sources_cache.json"
old = json.loads(CACHE.read_text(encoding="utf-8")) if CACHE.exists() else {}


def fetch(doi):
    url = "https://api.crossref.org/works/" + urllib.parse.quote(doi, safe="")
    for attempt in range(4):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "G51-evidence-review/1.0 (research data)"})
            with urllib.request.urlopen(req, timeout=30) as response:
                return doi, json.load(response)["message"]
        except Exception as exc:
            if attempt == 3:
                return doi, {"error": str(exc)}
            time.sleep(2 ** attempt)


with concurrent.futures.ThreadPoolExecutor(max_workers=4) as pool:
    for doi, data in pool.map(fetch, [d for d in DOIS if d not in old]):
        old[doi] = data
CACHE.write_text(json.dumps(old, ensure_ascii=False, indent=2), encoding="utf-8")

def item(source_id, citation, year, doi, source_type, strain, experiment, genes, reactions, measured, score, limit, url):
    return {"Source ID": source_id, "Full citation": citation, "Year": year, "DOI": doi, "Source type": source_type,
            "Strain": strain, "Experimental type": experiment, "Genes / proteins studied": genes,
            "Related Reaction IDs / candidate IDs": reactions, "What was directly measured": measured,
            "Applicable confidence level": score, "Evidence limitation": limit, "URL": url}

sources = [
    item("G51-S001", "NCBI RefSeq GCF_049532655.1, genomic.gff, annotation RS_2025_04_13", 2025, "", "Official annotation", "ATCC 23270", "Genome annotation", "RU820_RS00005–RU820_RS01505", "G51 identity", "Chromosome positions, locus, WP and product annotations", "Not a reaction score", "Protein function labels are computational annotations.", "https://drive.google.com/file/d/19ijnng4VELvWQH8QID6cII9TqYMUhes4/view"),
    item("G51-S002", "B1 old AFE to current RU820 mapping, project verified table", 2026, "", "Sequence/identity mapping", "ATCC 23270", "Protein ID exact matches; ambiguous mappings retained", "G51 old AFE", "Legacy tracking", "Old/current protein ID relationships", "Not a reaction score", "Protein identity does not prove catalysis; nonunique WP mapping is unresolved.", "B1_最新基因组与旧AFE编号映射/标准化数据/旧新基因映射.tsv"),
    item("G51-S003", "Campodonico et al. 2016 iMC507 original Supplementary Table 1", 2016, "10.1016/j.meteno.2016.03.003", "Model supplementary table", "ATCC 23270", "Model reconstruction", "Original AFE GPRs", "57 distinct G51-associated reactions after sequence reconciliation", "Reaction formula, score, EC, PMID, GPR and three media bounds", "Original scores only", "Old model score does not establish newly proposed gene links or revised chemistry.", "https://drive.google.com/file/d/1u23dFDLoG27LJvEi6BjYKIK3Tr-zR2-f/view"),
    item("G51-S004", "UniProtKB ATCC 23270 taxon 243159 protein records, accessed 2026-09-25", 2026, "", "Protein function database", "ATCC 23270", "Reviewed/unreviewed annotation and cross-references", "WP matched to UniProt accession", "All genes with UniProt hit", "Protein names, evidence codes, EC, InterPro/Pfam links", "2 for sequence-based precise reaction only", "Reviewed entries can still use sequence rules; paper evidence must be checked per assertion.", "https://rest.uniprot.org/uniprotkb/search"),
    item("G51-S005", "InterPro/Pfam family records from UniProtKB cross-references, accessed 2026-09-25", 2026, "", "Protein domain database", "Multiple organisms", "Domain/family classification", "G51 UniProt-linked proteins", "Domain candidates", "Family/domain accessions", "2 at most for precise reaction", "Family identity alone does not fix substrate, location or direction.", "https://www.ebi.ac.uk/interpro/"),
    item("G51-S006", "KEGG afr historical gene/KO/EC/reaction exports, project frozen 2026-09-22", 2026, "", "Metabolic annotation database", "ATCC 23270 old assembly", "Computational pathway mapping", "Old AFE matched by B1", "Candidate reaction IDs", "Gene-to-KO/EC/reaction links", "2 at most", "Old locus/version and inherited annotations require independent checking.", "https://www.kegg.jp/entry/afr"),
    item("G51-S007", "BioCyc AFER243159 PGDB 30.0 project export", 2026, "", "Metabolic annotation database", "ATCC 23270 old assembly", "PathoLogic computational predictions", "Old AFE matched by B1", "Candidate reaction IDs", "Old gene/protein/reaction associations", "2 at most", "BioCyc/MetaCyc Pathway Tools links share provenance and are not independent experiments.", "https://biocyc.org/AFER243159/"),
    item("G51-S008", "Rhea reaction definitions and ChEBI cross-references, project frozen 2026-09-23", 2026, "", "Reaction chemistry database", "General enzyme definitions", "Curated reaction stoichiometry", "EC-linked candidate proteins", "RHEA accessions", "Equations, ChEBI IDs and EC links", "No gene-specific score", "Exact chemical definition does not prove this locus catalyzes it.", "https://www.rhea-db.org/"),
    item("G51-S009", "BRENDA organism/EC project exports, accessed 2026-09-23", 2026, "", "Enzyme database", "Organism-dependent", "EC and reaction records", "G51 EC candidates", "Candidate enzyme chemistry", "EC-level data", "Depends on underlying paper", "Organism-level records cannot be assigned to an exact locus without gene/protein evidence.", "https://www.brenda-enzymes.org/"),
    item("G51-S010", "Europe PMC per-gene ID and functional phrase searches, accessed 2026-09-25", 2026, "", "Literature index", "Mixed strains", "Search index only", "293 G51 loci", "Paper leads", "DOI/title/abstract candidates", "No reaction score", "Zero hits do not prove no study; hits require strain, gene and assay verification.", "https://www.ebi.ac.uk/europepmc/webservices/rest/search"),
    item("G51-S011", "TCDB domain-restricted exact WP accession searches, accessed 2026-09-25", 2026, "", "Transporter database search", "Mixed organisms", "21 exact WP site searches", "21 G51 transporter candidates", "Transporter class leads", "No exact WP-indexed TCDB result observed", "No reaction score", "Web-index absence does not exclude an unindexed TCDB homolog; family names do not prove substrate, direction or coupling.", "https://tcdb.org/"),
    item("G51-S012", "Frozen GCF_049532655.1 vs GCF_000021485.1 protein sequence alignment, G51 2026-09-25", 2026, "", "Current-to-legacy sequence reconciliation", "ATCC 23270 two assemblies", "Local protein sequence alignment plus both frozen genomic GFFs", "15 previously ambiguous G51 loci", "2016 GPR traceability", "Identity and coverage; recovered old AFE_0208 to RU820_RS01005 and partial AFE_0141 to RU820_RS00670", "Identity only, no reaction score", "Partial sequence and historical gene model cannot transfer the old full-length enzyme function; duplicate WP mapping remains ambiguous.", "G51_sequence_reconciled_2016.json"),
    item("G51-S013", "Europe PMC exact current RU820 and WP identifier search, G51 2026-09-26", 2026, "", "Literature index", "Mixed organisms", "586 current-ID searches for 293 G51 genes", "All 293 G51 current loci and WP accessions", "Original paper leads", "One WP_009565301.1 hit in a deep-sea microbiome study; no G51-specific direct reaction experiment", "No reaction score", "Absence of exact-ID search results does not establish absence of literature under gene names or unpublished experiments.", "europe_pmc_current_id_search.json"),
    item("G51-S014", "ExPASy ENZYME current EC nomenclature, accessed 2026-09-26", 2026, "", "Enzyme nomenclature database", "General enzyme classes", "Official EC reaction and substrate definitions", "G51 conflicting EC annotations", "EC 6.1.1.12/23; 3.1.2.20/23; 2.3.2.8/29", "Distinct tRNA/protein acceptors and acyl donors specified by different EC numbers", "Nomenclature only, no locus-specific score", "EC definitions separate reactions but cannot determine which specific G51 WP performs them.", "https://enzyme.expasy.org/"),
    item("G51-S015", "NCBI Protein BAC66780.1 FopA versus RefSeq WP_009567335.1 frozen GCF_049532655.1 sequence alignment, 2026-09-26", 2026, "", "Historical-to-current protein alignment", "A. ferrooxidans", "Full-length protein pairwise alignment", "FopA/BAC66780.1; RU820_RS01485/WP_009567335.1", "Literature identity reconciliation", "217 aa each, 212 identical, 5 substitutions, no gaps", "Identity evidence, no reaction score", "Sequence similarity transfers the FopA protein identification; it does not validate a transport substrate or flux.", "https://www.ncbi.nlm.nih.gov/protein/BAC66780.1"),
]

context = {
 "10.1016/j.resmic.2008.04.002": ("A. ferrooxidans LR genes; ATCC 23270 genome compared", "RibB/RibBA cloning and transcript measurement under nutrient, metal, pH and temperature conditions", "ribBA homolog AFE_0299; ribB is outside G51", "DB4PS;GTPCII2", "Expression changes and genomic organization; no purified RibBA catalytic assay", "2 for ATCC 23270 exact chemistry from annotation; expression evidence is not biochemical level 4", "The cloned gene was from strain LR and the paper did not measure either specific reaction of ATCC 23270 WP_012536073.1."),
 "10.1007/s00792-011-0371-6": ("ATCC 23270", "FopA cloning, outer membrane localization, oligomerization and recombinant peptidoglycan binding", "fopA; AFE_0306/RU820_RS01485 supported by historical FopA sequence match", "No specific transport reaction", "ATCC 23270 FopA peptidoglycan binding and outer membrane protein behavior", "3 for protein function; no stoichiometric metabolic reaction score", "Paper does not establish FopA pore activity, transported substrate or exact reaction."),
 "10.1074/jbc.M802496200": ("A. ferrooxidans iron-respiratory complex", "Native supercomplex purification and proteomic identification", "FopA historical protein GI 29467513/BAC66780.1; AFE_0306", "No FopA-catalyzed reaction", "Two FopA peptides in BN-gel complex fraction; iron respiration attributed to other members", "Protein detection only, no FopA reaction score", "FopA may be associated or a copurifying protein; no FopA-specific pore or chemical assay."),
 "10.1186/1471-2164-9-597": ("ATCC 23270", "Genome annotation and pathway analysis", "AFE_0105/MntH-like NRAMP", "MN2tpp;MNTH;CU2tpp;ZN2tpp", "Proposed dual Mn(II)/Fe(II) transporter from genome context", "2 for Mn/Fe transporter hypothesis; none for Cu/Zn precise import", "No AFE_0105 direct uptake assay, metal specificity measurement, or proton-coupling measurement."),
 "10.1038/s41598-022-16468-w": ("M. tuberculosis and S. aureus MetX; not ATCC 23270", "Purified homoserine acyltransferase substrate assay", "MetX homologs", "HSERTA donor specificity", "Acetyl-CoA preferred over succinyl-CoA in the tested homolog", "2 at most as family context", "The tested protein is not RU820_RS01420; donor specificity of the G51 protein requires direct assay."),
 "10.1128/jb.187.6.2215-2217.2005": ("Staphylococcus aureus, not ATCC 23270", "Purified PBP2 glycan-polymerization assay", "PBP2, contrasted with MurG", "PGLT;UCMAT", "Lipid-II glycan polymerization by a class A PBP", "2 for enzyme-family role distinction", "Does not directly assay the G51 MurG or identify the G51 polymerase."),
 "10.3389/fmicb.2019.01642": ("ATCC 23270 gene cloned; E. coli host assays", "AFE_0270 FNR cloning, complementation, promoter reporter and Fe-S spectroscopy", "AFE_0270/FNR_AF", "Regulatory protein; no stoichiometric metabolic reaction", "FNR_AF restored FNR-dependent reporter activity in E. coli and bound an Fe-S cluster", "3 for functional regulator evidence; no metabolic reaction score", "Heterologous reporter and spectroscopy do not identify a direct substrate-converting reaction for a metabolic model."),
 "10.3389/fmicb.2017.01277": ("ATCC 23270", "RegB/RegA promoter and expression analysis", "AFE_0027 regulator proposed in tet operon", "No AFE_0027 metabolic reaction", "RegA-mediated regulation measured; AFE_0027 involvement proposed from location and sigma-54 promoter", "2 for AFE_0027 regulatory hypothesis", "No direct AFE_0027 knockout, binding or metabolite conversion reported."),
 "10.3389/fmicb.2016.01365": ("ATCC 23270", "Quorum-sensing analog treatment, qPCR and transcriptomics", "AFE_0233 glycosyltransferase candidate", "No specific AFE_0233 glycosyltransfer reaction", "AFE_0233 transcript measured and not significantly changed in the tested condition", "2 for expression/existence, no reaction score", "Transcript abundance and a family annotation do not identify glycan acceptor/donor or reaction stoichiometry."),
 "10.1371/journal.pone.0112226": ("ATCC 23270 genome; heterologous assays on different ICEAfe1 loci", "Toxin-antitoxin family classification and selected heterologous toxin assays", "AFE_0085;AFE_0086;AFE_0088;AFE_0089 among genome candidates", "No G51 metabolic reaction", "Family assignment of G51 toxin-antitoxin candidates; functional assays focused on AFE_13xx ICEAfe1 loci", "2 for G51 family classification; no precise reaction score", "The tested RNase toxins are different loci; cannot transfer their activity to these four G51 proteins."),
 "10.3389/fmicb.2019.00592": ("DSM 14882 = ATCC 23270", "Pyrite biofilm versus Fe(II) planktonic quantitative proteomics", "AFE_0024;AFE_0135;AFE_0156;AFE_0199;AFE_0247;AFE_0282", "No exact G51 reaction measured", "Condition-dependent relative abundance of several G51 proteins", "Protein detection/abundance only; no precise reaction score", "Proteomics does not establish biochemical substrates or reaction equations, and legacy peptide-to-current-WP identity requires sequence verification where descriptions differ."),
 "10.3389/fmicb.2022.960324": ("Polar/subpolar A. ferrooxidans PG05 and MC2.2 compared with ATCC 23270", "Comparative genomics and metal tolerance", "AFE_0022 historical annotation", "No exact G51 reaction", "Table lists AFE_0022 as a putative cation channel in the ATCC reference", "Annotation only, no precise reaction score", "No uptake assay for current RU820_RS00115/WP; current official product is DUF4390 and specific ion is unknown."),
 "10.3389/fmicb.2018.03290": ("Multiple Acidithiobacillus species", "Review of sulfur oxidation studies", "AFE_0050 putative paralog of AFE_0042 TSD", "TSD candidate, no in vivo acceptor established", "Reports 76% sequence identity of AFE_0050 to measured AFE_0042 and treats it as potential TSD", "2 for homolog candidate, not a direct assay", "Review repeats homology inference; no purified AFE_0050 assay or q8-dependent exact reaction."),
 "10.3389/fmicb.2016.02035": ("ATCC 23270 plus other Acidithiobacillus genomes", "Orphan core protein family bioinformatics", "AFE_0294", "No exact G51 reaction", "Places AFE_0294 in conserved family I with five predicted transmembrane segments", "Family inference only", "No AFE_0294 substrate, transporter direction, or catalytic experiment; expression support is from other strains/environmental datasets."),
 "10.1016/j.jbiotec.2007.08.030": ("ATCC 23270", "Native enzyme purification, N-terminal protein identification", "AFE_0029/TetH", "4THASE1;4THASE2", "Tetrathionate-dependent activity and purified protein N-terminus", "4 for measured hydrolysis; exact alternative formula ratios require check", "No proof for all legacy product ratios."),
 "10.1128/JB.01472-13": ("ATCC 23270", "tetH knockout, complementation, overexpression and qPCR", "AFE_0029;AFE_0048", "4THASE1;4THASE2;TSQOC", "Tetrathionate-growth phenotype and doxD transcript changes", "3 for TetH physiological hydrolysis", "Transcription of doxD does not prove its precise reaction or complex composition."),
 "10.1128/AEM.02251-12": ("ATCC 23270", "Purified/recombinant thiosulfate dehydrogenase assay", "AFE_0042", "TSQOC", "Thiosulfate-to-tetrathionate assay with ferricyanide; quinone negative", "4 for the measured artificial-acceptor assay", "Does not validate q8-dependent 2016 TSQOC equation."),
 "10.1007/s00253-014-5830-4": ("ATCC 23270; A. caldus MTH-04", "Recombinant enzyme assay and ATCC 23270 knockout/overexpression", "AFE_0269", "RHEA:12981;SULDO", "GSH-dependent SDO activity, sulfur-growth/activity effects", "4 for measured assay; lower for exact GSSH model equation", "GSSH in vivo and compartment were not established."),
 "10.1074/jbc.M700374200": ("Other bacterial PlsY", "Membrane topology and active-site biochemical study", "PlsY homolog", "G3PAT1 candidate", "Acylphosphate:glycerol-3-phosphate acyltransferase specificity", "2 for ATCC 23270 inference", "Other organism; no ATCC 23270 substrate assay."),
 "10.1021/bi00136a016": ("Escherichia coli", "Purified PurE/PurK/PurC biochemistry", "PurE;PurK homologs", "AIRC;RHEA:13193;RHEA:19317", "Two-step ATP-dependent AIR-to-CAIR chemistry", "2 for ATCC 23270 inference", "Other organism; no direct ATCC 23270 assay."),
 "10.3389/fmicb.2019.00603": ("ATCC 23270", "Whole-cell CO2 uptake/assimilation, expression, SulP/Can2 phylogenomics", "AFE_0286 SulP; AFE_0287 Can2", "SO42tpp; bicarbonate transport candidate; HCO3E", "CO2 response and can2/sulP expression; phylogeny places SulP with bicarbonate transporters", "2 for competing bicarbonate transport annotation; 1 for unsupported sulfate exact transport", "No isolated SulP sulfate/bicarbonate uptake assay, coupling-ion measurement or direct Can2 catalytic assay."),
 "10.1074/jbc.M113.480368": ("Escherichia coli", "UbiI gene perturbation and ubiquinone intermediate analysis", "UbiI/UbiB homolog context", "OPHHX", "UbiI hydroxylation role and correction of old UbiB assignment", "2 for ATCC 23270 functional inference", "Other organism; does not identify the ATCC 23270 hydroxylase."),
 "10.1128/aem.00170-25": ("ATCC 23270", "AFE_0267 and AFE_1792 overexpression; aerobic and anaerobic sulfur growth and sulfur species", "AFE_0267", "SQRED1;RHEA:30239", "AFE_0267 overexpression increased sulfur oxidation and iron reduction under anaerobic conditions, without an aerobic increase", "3 for gene-related sulfur-oxidation phenotype; 2 for a proposed exact quinone reaction", "No purified AFE_0267 assay, measured quinone donor/acceptor, or compartment-specific reaction; AFE_1792 is outside G51."),
 "10.1128/aem.02288-25": ("ATCC 23270", "Published AFE_0053 overexpression/c-di-GMP; AFE_0090 transcript response", "Published AFE_0053; AFE_0090 annotation also conflicts with current WP", "Diguanylate cyclase candidate, not assigned; no AFE_0090 reaction", "AFE_0053 overexpression raised cellular c-di-GMP; paper categorized AFE_0090 as pilus-associated and reported transcript increase", "No G51 precise reaction score while protein identity/function conflicts", "The current AFE_0053-to-WP maps to YeeE/YedE despite published DGC claims; current AFE_0090 maps to HNH endonuclease despite paper pilus label. Historical sequences need comparison."),
 "10.4028/www.scientific.net/AMR.20-21.551": ("ATCC 23270 genome", "Sequence motif analysis and RT-PCR", "Published AFE_0053 841-aa GGDEF/EAL protein", "Diguanylate cyclase candidate, identity disputed", "Predicted DGC motifs and expression", "No G51 reaction score while protein identity conflicts", "Published AFE_0053 length and domains conflict with current exact-WP AFE_0053 mapping."),
 "10.1074/mcp.M700042-MCP200": ("ATCC 23270", "Periplasmic proteomics during thiosulfate growth", "Eight published AFE IDs matching G51 old IDs, all identity-disputed", "No G51 reaction assigned", "Periplasmic protein detections and predicted-function discussion using TIGR-era AFE identifiers", "No G51 reaction score while protein identity conflicts", "The eight paper protein descriptions conflict with current exact-WP mapping; mass-spectrometry peptides or historical sequences must be reconciled with frozen current proteins."),
 "10.3389/fmicb.2011.00079": ("ATCC 23270", "Oxygen-limited thiosulfate cultures; extracellular tetrathionate hydrolase assay and TetH mass spectrometry", "TetH/AFE_0029", "4THASE1;4THASE2", "Extracellular tetrathionate loss, sulfur globules, supernatant hydrolase activity and TetH protein", "3 for gene-associated overall hydrolysis; not 4 for unmeasured exact alternative coefficients", "Whole culture and supernatant products include downstream abiotic chemistry; neither 2016 equation's exact coefficients are directly established."),
 "10.1186/1471-2164-10-394": ("ATCC 23270", "Genome-based sulfur oxidation pathway modeling", "AFE_0041–AFE_0046; nearby AFE_0049", "TSQOC; no precise AFE_0049 reaction", "Proposed gene cluster and electron-flow network", "2 for annotation-level hypotheses only", "A pathway diagram does not establish a six-subunit catalytic complex, quinone acceptor, or AFE_0049 substrate/transport direction."),
 "10.1074/jbc.M400596200": ("ATCC 23270 gene source; recombinant proteins in E. coli", "GnnA/GnnB cloning, enzymatic conversion and NMR product identification", "GnnA; GnnB; not G51 LpxC/Kdo transferase/acyltransferase", "2016 UAAD;KDOCT;KDOCT3;LDAS;LIPS cite this PMID", "UDP-GlcNAc conversion to UDP-GlcNAc3N by GnnA plus GnnB", "No direct score for these five G51 reactions", "The 2016 PMID is a pathway-context citation and cannot confer experimental reaction evidence on other proteins."),
 "10.1128/jb.123.2.642-650.1975": ("Thiobacillus ferrooxidans isolate identity not established as ATCC 23270", "Whole-cell lipopolysaccharide physical and chemical analysis", "No acetyl-CoA carboxylase gene or protein", "2016 BIOC1 cites this PMID", "LPS composition under different growth substrates", "No BIOC1 reaction score", "The paper does not assay acetyl-CoA carboxylation, identify the G51 proteins, or validate the old BIOC1 GPR."),
}

for n, doi in enumerate(DOIS, 1):
    meta = old[doi]
    authors = ", ".join(" ".join(filter(None, [a.get("given", ""), a.get("family", "")])) for a in meta.get("author", []))
    title = (meta.get("title") or [doi])[0]
    journal = (meta.get("container-title") or [""])[0]
    year = (meta.get("published", {}).get("date-parts") or [[""]])[0][0]
    citation = f"{authors} ({year}). {title}. {journal}. https://doi.org/{doi}"
    strain, exp, genes, reactions, measured, score, limit = context[doi]
    kind = "Review" if doi == "10.3389/fmicb.2018.03290" else "Original research"
    sources.append(item(f"G51-P{n:03d}", citation, year, doi, kind, strain, exp, genes, reactions, measured, score, limit, "https://doi.org/" + doi))

(HERE / "G51_sources.json").write_text(json.dumps(sources, ensure_ascii=False, indent=2), encoding="utf-8")
(HERE / "G51_doi_source_ids.json").write_text(json.dumps({d: f"G51-P{i:03d}" for i, d in enumerate(DOIS, 1)}, ensure_ascii=False, indent=2), encoding="utf-8")
print("sources", len(sources), "DOIs", len(DOIS), "errors", [d for d in DOIS if "error" in old[d]])
